language: python
sudo: false
services:
  - mysql
  - postgresql
  - memcached
addons:
# Use postgresql 9.3 to get commit-lock testing
# Use postgresql 9.4 to get support for BLOB SQL functions for pg8000
  postgresql: "9.4"
python:
  - 2.7
  - 3.4
  - pypy
env:
  matrix:
    - ENV=mysql
    - ENV=postgres
    - ENV=pypostgres
    - ENV=pymysql
    - ENV=umysqldb
matrix:
  exclude:
    - python: 3.4
      env: ENV=umysqldb
    - python: pypy
      env: ENV=pymysql
    - python: pypy
      env: ENV=umysqldb
  fast_finish: true
script:
# coverage slows PyPy down from 2minutes to 12+.
# But don't run the pymysql/pypy tests twice.
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then python -m relstorage.tests.alltests -v; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then coverage run -m relstorage.tests.alltests -v; fi
after_success:
  - coveralls
notifications:
  email: false

install:
  - pip install -U pip setuptools
  - pip install -U tox coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install -U python-memcached; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install -U pylibmc cffi; fi
  - pip install -U -e ".[test]"
  - .travis/setup-$ENV.sh
# Install the latest stable versions of ZODB/ZEO together,
# without specifying to use beta versions. The caches on travis
# sometimes get in a weird state and we wind up with incompatible
# mixes while they are in beta mode (e.g., we get ZEO 5.0b1 but ZODB
# 4.4.3 for some reason)
  - pip install "ZODB<5" "ZEO<5"
# cache: pip seems not to work if `install` is replaced (https://github.com/travis-ci/travis-ci/issues/3239)
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.venv
    - $HOME/.runtimes
    - $HOME/.wheelhouse

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
