language: python
dist: xenial
group: travis_latest
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3

services:
  - mysql
  - postgresql
  - memcached
addons:
# Use postgresql 9.3 to get commit-lock testing
# Use postgresql 9.4 to get support for BLOB SQL functions for pg8000
# Use postgresql 9.5 to get support for INSERT ON CONFLICT UPDATE
# Use postgresql 9.6 ... just because
  postgresql: "9.6"

env:
    global:
        - PYTHONHASHSEED=8675309
        - CC="ccache gcc"
        - CCACHE_NOCPP2=true
        - CCACHE_SLOPPINESS=file_macro,time_macros,include_file_ctime,include_file_mtime
        - CCACHE_NOHASHDIR=true
        - CFLAGS="-g -pipe"

script:
# coverage slows PyPy down from 2minutes to 12+.
# But don't run the pymysql/pypy tests twice.
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pylint --rcfile=.pylintrc relstorage -f parseable -r n; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then python -m zope.testrunner --test-path=src --auto-color --auto-progress; fi
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run -m  zope.testrunner --test-path=src --auto-color --auto-progress; fi
after_success:
  - coveralls
notifications:
  email: false

before_install:
  - python --version
before_script:
  - ccache -s

install:
  - pip install -U pip
  - pip install -U setuptools wheel coveralls
  - pip install -U "pylint>=1.7.1"
  - pip install -U 'cffi; platform_python_implementation=="CPython"'
  - pip install -U -e ".[test,all_tested_drivers]"
  - .travis/postgres.sh
  - .travis/mysql.sh

cache:
  pip: true
  directories:
    - $HOME/.wheelhouse
    - $HOME/.ccache

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
